<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Billing.Invoicing.Domain\Billing.Invoicing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="Dapper" />
  </ItemGroup>

</Project>
